/**
 * Game Constants and Configuration
 * Design: Retro Arcade Cyberpunk
 */

import {
  Heart,
  Shield,
  Sword,
  Coins,
  Skull,
  Store,
  Hammer,
  Zap,
  Shirt,
  Sparkles,
  Gift,
  Lock,
  Droplets,
  Flame,
  Star,
  Cross,
  Wand,
  Package,
} from 'lucide-react';

export const GAME_STATE = {
  MENU: 'MENU',
  CLASS_SELECT: 'CLASS_SELECT',
  ZONE_SELECT: 'ZONE_SELECT',
  MAP: 'MAP',
  COMBAT: 'COMBAT',
  VICTORY: 'VICTORY',
  GAME_OVER: 'GAME_OVER',
} as const;

export const MODAL_STATE = {
  NONE: 'NONE',
  INVENTORY: 'INVENTORY',
  SHOP: 'SHOP',
  STATS: 'STATS',
} as const;

export const CLASSES_DB = {
  warrior: {
    id: 'warrior',
    name: 'Chiến Binh',
    icon: Sword,
    color: 'text-red-500',
    desc: 'Bậc thầy cận chiến. Sức chống chịu cao.',
    baseMod: { atk: 2, def: 2, maxHp: 30, luck: 0 },
    allowed: { weapon: ['SWORD', 'AXE'], armor: ['HEAVY', 'PLATE'] },
    passiveDesc: 'Khởi đầu trận đấu với lớp Giáp ảo (10).',
    skills: [
      {
        id: 'bash',
        name: 'Khiên Thịt',
        max: 5,
        desc: '+2 DEF vĩnh viễn',
        type: 'PASSIVE',
        mod: { def: 2 },
      },
      {
        id: 'frenzy',
        name: 'Điên Cuồng',
        max: 3,
        desc: '+10% Crit Chance',
        type: 'PASSIVE',
        mod: { crit: 10 },
      },
    ],
  },
  rogue: {
    id: 'rogue',
    name: 'Sát Thủ',
    icon: Skull,
    color: 'text-green-400',
    desc: 'Nhanh nhẹn và may mắn. Gây sát thương chí mạng.',
    baseMod: { atk: 4, def: 0, maxHp: -10, luck: 5, crit: 10 },
    allowed: { weapon: ['DAGGER', 'BOW'], armor: ['LIGHT', 'LEATHER'] },
    passiveDesc: 'Đòn đánh có 20% tỉ lệ gây Độc.',
    skills: [
      {
        id: 'lucky',
        name: 'Bàn Tay Vàng',
        max: 5,
        desc: '+2 LUCK vĩnh viễn',
        type: 'PASSIVE',
        mod: { luck: 2 },
      },
      {
        id: 'lethal',
        name: 'Tử Huyệt',
        max: 3,
        desc: '+20% Crit Damage (giả lập qua ATK)',
        type: 'PASSIVE',
        mod: { atk: 5 },
      },
    ],
  },
  mage: {
    id: 'mage',
    name: 'Pháp Sư',
    icon: Wand,
    color: 'text-purple-400',
    desc: 'Sức mạnh phép thuật hủy diệt nhưng máu thấp.',
    baseMod: { atk: 8, def: -1, maxHp: -20, luck: 2 },
    allowed: { weapon: ['STAFF', 'WAND'], armor: ['ROBE', 'CLOTH'] },
    passiveDesc: 'Đòn đánh có tỉ lệ gây hiệu ứng ngẫu nhiên.',
    skills: [
      {
        id: 'glass',
        name: 'Thủy Tinh',
        max: 3,
        desc: '+5 ATK, -10 HP',
        type: 'PASSIVE',
        mod: { atk: 5, maxHp: -10 },
      },
      {
        id: 'wisdom',
        name: 'Thông Thái',
        max: 5,
        desc: 'Tăng hiệu quả hồi năng lượng (HP Regen)',
        type: 'PASSIVE',
        mod: { hpRegen: 2 },
      },
    ],
  },
  cleric: {
    id: 'cleric',
    name: 'Mục Sư',
    icon: Cross,
    color: 'text-yellow-400',
    desc: 'Khả năng hồi phục và sinh tồn tuyệt vời.',
    baseMod: { atk: 0, def: 3, maxHp: 40, luck: 0 },
    allowed: { weapon: ['MACE', 'STAFF'], armor: ['ROBE', 'PLATE'] },
    passiveDesc: 'Hiệu quả sử dụng thuốc tăng 50%.',
    skills: [
      {
        id: 'faith',
        name: 'Đức Tin',
        max: 5,
        desc: '+10 Max HP',
        type: 'PASSIVE',
        mod: { maxHp: 10 },
      },
      {
        id: 'guardian',
        name: 'Hộ Vệ',
        max: 3,
        desc: '+3 DEF',
        type: 'PASSIVE',
        mod: { def: 3 },
      },
    ],
  },
} as const;

export const ZONES_DB = [
  {
    id: 'z_forest',
    name: 'Rừng Độc',
    difficulty: 0,
    desc: 'Quái vật gây Độc.',
    color: 'text-green-400',
    bg: 'from-green-900 to-slate-900',
  },
  {
    id: 'z_ruins',
    name: 'Tàn Tích',
    difficulty: 2,
    desc: 'Quái vật gây Choáng.',
    color: 'text-yellow-400',
    bg: 'from-yellow-900 to-slate-900',
  },
  {
    id: 'z_dungeon',
    name: 'Hầm Ngục',
    difficulty: 5,
    desc: 'Quái vật gây Suy Yếu.',
    color: 'text-purple-400',
    bg: 'from-purple-900 to-slate-900',
  },
  {
    id: 'z_hell',
    name: 'Địa Ngục',
    difficulty: 10,
    desc: 'Thử thách cực đại.',
    color: 'text-red-500',
    bg: 'from-red-900 to-orange-900',
  },
];

export const EFFECTS_DB = {
  STRONG_ATK: {
    id: 'eff_strong',
    name: 'Tăng Lực',
    type: 'BUFF',
    icon: Sword,
    color: 'text-red-400',
    desc: '+5 ATK',
    mods: { atk: 5 },
  },
  REGEN: {
    id: 'eff_regen',
    name: 'Hồi Phục',
    type: 'BUFF',
    icon: Heart,
    color: 'text-pink-400',
    desc: '+3 HP/lượt',
    dot: { type: 'HP_FLAT', val: 3 },
  },
  POISON: {
    id: 'eff_poison',
    name: 'Trúng Độc',
    type: 'DEBUFF',
    icon: Droplets,
    color: 'text-green-400',
    desc: '-4 HP/lượt',
    dot: { type: 'HP_FLAT', val: -4 },
  },
  SHIELD: {
    id: 'eff_shield',
    name: 'Lá Chắn',
    type: 'BUFF',
    icon: Shield,
    color: 'text-blue-300',
    desc: 'Hấp thụ 20 ST',
    shieldVal: 20,
  },
  STUN: {
    id: 'eff_stun',
    name: 'Choáng',
    type: 'DEBUFF',
    icon: Star,
    color: 'text-yellow-400',
    desc: 'Mất lượt',
    isStun: true,
  },
  VULNERABLE: {
    id: 'eff_vuln',
    name: 'Suy Yếu',
    type: 'DEBUFF',
    icon: Shield,
    color: 'text-purple-400',
    desc: '+20% ST nhận vào',
    incomingPercent: 20,
  },
  BURN: {
    id: 'eff_burn',
    name: 'Cháy',
    type: 'DEBUFF',
    icon: Flame,
    color: 'text-orange-500',
    desc: '-3 HP/lượt',
    dot: { type: 'HP_FLAT', val: -3 },
  },
} as const;

export const ROOM_TYPES = {
  START: { icon: '→', color: 'text-white', label: 'Lối Vào' },
  COMBAT: { icon: '⚔', color: 'text-slate-300', label: 'Quái Vật' },
  ELITE: { icon: '💀', color: 'text-red-400', label: 'Tinh Anh' },
  TREASURE: { icon: '💎', color: 'text-yellow-400', label: 'Kho Báu' },
  SHOP: { icon: '🏪', color: 'text-blue-400', label: 'Cửa Hàng' },
  BOSS: { icon: '⚡', color: 'text-purple-500', label: 'TRÙM' },
} as const;

export const MOVES = {
  ROCK: { id: 'rock', name: 'Búa', icon: '✊', beats: 'scissors', color: 'text-orange-500' },
  PAPER: { id: 'paper', name: 'Bao', icon: '✋', beats: 'rock', color: 'text-green-500' },
  SCISSORS: {
    id: 'scissors',
    name: 'Kéo',
    icon: '✌️',
    beats: 'paper',
    color: 'text-blue-500',
  },
} as const;

export const RARITY_CONFIG = {
  1: {
    name: 'Thường',
    color: 'border-slate-500 text-slate-300',
    bg: 'bg-slate-800',
    affixes: 0,
    weight: 60,
  },
  2: {
    name: 'Hiếm',
    color: 'border-green-500 text-green-400',
    bg: 'bg-slate-800',
    affixes: 1,
    weight: 30,
  },
  3: {
    name: 'Cao Cấp',
    color: 'border-blue-500 text-blue-400',
    bg: 'bg-slate-900',
    affixes: 2,
    weight: 15,
  },
  4: {
    name: 'Sử Thi',
    color: 'border-purple-500 text-purple-400',
    bg: 'bg-slate-900',
    affixes: 3,
    weight: 5,
  },
  5: {
    name: 'Huyền Thoại',
    color: 'border-orange-500 text-orange-400',
    bg: 'bg-slate-950',
    affixes: 4,
    weight: 1,
  },
} as const;

export const AFFIX_DB: any[] = [
  { id: 'sharp', name: 'Sắc Bén', stat: 'atk', val: 1, type: ['WEAPON'] },
  { id: 'heavy', name: 'Nặng Ký', stat: 'atk', val: 2, type: ['WEAPON'] },
  { id: 'lethal', name: 'Chí Mạng', stat: 'crit', val: 3, type: ['WEAPON', 'ACCESSORY'] },
  { id: 'hard', name: 'Cứng Cáp', stat: 'def', val: 1, type: ['ARMOR'] },
  { id: 'vital', name: 'Sinh Lực', stat: 'maxHp', val: 10, type: ['ARMOR', 'ACCESSORY'] },
  { id: 'lucky', name: 'May Mắn', stat: 'luck', val: 1, type: ['ACCESSORY', 'WEAPON'] },
];

export const MONSTER_PREFIXES = [
  'Hư Không',
  'Bóng Tối',
  'Rực Lửa',
  'Băng Giá',
  'Độc Dược',
  'Cuồng Nộ',
  'Cổ Đại',
];

export const MONSTER_TYPES = [
  'Slime',
  'Goblin',
  'Bộ Xương',
  'Dơi',
  'Sói',
  'Orc',
  'Phù Thủy',
  'Golem',
  'Rồng',
];

export const ITEMS_DB: any[] = [
  {
    id: 'pot_small',
    name: 'Binh Mau Nho',
    type: 'CONSUMABLE',
    baseCost: 20,
    rarity: 1,
    desc: 'Hoi 30 HP',
    icon: '❤️',
  },
  {
    id: 'pot_large',
    name: 'Binh Mau Lon',
    type: 'CONSUMABLE',
    baseCost: 50,
    rarity: 2,
    desc: 'Hoi 80 HP',
    icon: '🍷',
  },
  {
    id: 'respec',
    name: 'Sach Lang Quan',
    type: 'CONSUMABLE',
    baseCost: 500,
    rarity: 4,
    desc: 'Reset diem',
    icon: '📖',
  },
  {
    id: 'pot_str',
    name: 'Thuoc Suc Manh',
    type: 'CONSUMABLE',
    baseCost: 40,
    rarity: 2,
    desc: '+5 ATK (3 luot)',
    icon: '⚔️',
  },
  {
    id: 'scroll_shield',
    name: 'Cuon Bao Ve',
    type: 'CONSUMABLE',
    baseCost: 60,
    rarity: 3,
    desc: 'Tao giap ao 20',
    icon: '📜',
  },
  {
    id: 'w_sword',
    name: 'Kiem Sat',
    type: 'WEAPON',
    subType: 'SWORD',
    baseCost: 50,
    rarity: 1,
    baseStats: { atk: 4 },
    icon: '🗡️',
  },
  {
    id: 'w_axe',
    name: 'Riu Chien',
    type: 'WEAPON',
    subType: 'AXE',
    baseCost: 60,
    rarity: 2,
    baseStats: { atk: 6 },
    icon: '🪓',
  },
  {
    id: 'w_dagger',
    name: 'Dao Gam',
    type: 'WEAPON',
    subType: 'DAGGER',
    baseCost: 40,
    rarity: 1,
    baseStats: { atk: 3, crit: 5 },
    icon: '🔪',
  },
  {
    id: 'w_staff',
    name: 'Gay Phep',
    type: 'WEAPON',
    subType: 'STAFF',
    baseCost: 55,
    rarity: 2,
    baseStats: { atk: 5 },
    icon: '🦯',
  },
  {
    id: 'a_plate',
    name: 'Giap Tam',
    type: 'ARMOR',
    subType: 'PLATE',
    baseCost: 80,
    rarity: 2,
    baseStats: { def: 4, maxHp: 20 },
    icon: '🛡️',
  },
  {
    id: 'a_robe',
    name: 'Ao Vai',
    type: 'ARMOR',
    subType: 'ROBE',
    baseCost: 30,
    rarity: 1,
    baseStats: { def: 1, maxHp: 10 },
    icon: '👘',
  },
  {
    id: 'a_leather',
    name: 'Giap Da',
    type: 'ARMOR',
    subType: 'LEATHER',
    baseCost: 40,
    rarity: 1,
    baseStats: { def: 2, maxHp: 15 },
    icon: '🧥',
  },
  {
    id: 'ac_ring',
    name: 'Nhan Luc',
    type: 'ACCESSORY',
    baseCost: 100,
    rarity: 2,
    baseStats: { atk: 2, luck: 1 },
    icon: '💍',
  },
];
