import { Cross, Skull, Sword, Wand } from "lucide-react";

export const CLASSES_DB = {
  warrior: {
    id: "warrior",
    name: "Chiến Binh",
    icon: Sword,
    color: "text-red-500",
    desc: "Bậc thầy cận chiến. Sức chống chịu cao.",
    baseMod: { atk: 2, def: 2, maxHp: 30, luck: 0 },
    allowed: { weapon: ["SWORD", "AXE"], armor: ["HEAVY", "PLATE"] },
    passiveDesc: "Khởi đầu trận đấu với lớp Giáp ảo (10).",
    skills: [
      {
        id: "bash",
        name: "Khiên Thịt",
        max: 5,
        desc: "+2 DEF vĩnh viễn",
        type: "PASSIVE",
        mod: { def: 2 },
      },
      {
        id: "frenzy",
        name: "Điên Cuồng",
        max: 3,
        desc: "+10% Crit Chance",
        type: "PASSIVE",
        mod: { crit: 10 },
      },
    ],
  },
  rogue: {
    id: "rogue",
    name: "Sát Thủ",
    icon: Skull,
    color: "text-green-400",
    desc: "Nhanh nhẹn và may mắn. Gây sát thương chí mạng.",
    baseMod: { atk: 4, def: 0, maxHp: -10, luck: 5, crit: 10 },
    allowed: { weapon: ["DAGGER", "BOW"], armor: ["LIGHT", "LEATHER"] },
    passiveDesc: "Đòn đánh có 20% tỉ lệ gây Độc.",
    skills: [
      {
        id: "lucky",
        name: "Bàn Tay Vàng",
        max: 5,
        desc: "+2 LUCK vĩnh viễn",
        type: "PASSIVE",
        mod: { luck: 2 },
      },
      {
        id: "lethal",
        name: "Tử Huyệt",
        max: 3,
        desc: "+20% Crit Damage (giả lập qua ATK)",
        type: "PASSIVE",
        mod: { atk: 5 },
      },
    ],
  },
  mage: {
    id: "mage",
    name: "Pháp Sư",
    icon: Wand,
    color: "text-purple-400",
    desc: "Sức mạnh phép thuật hủy diệt nhưng máu thấp.",
    baseMod: { atk: 8, def: -1, maxHp: -20, luck: 2 },
    allowed: { weapon: ["STAFF", "WAND"], armor: ["ROBE", "CLOTH"] },
    passiveDesc: "Đòn đánh có tỉ lệ gây hiệu ứng ngẫu nhiên.",
    skills: [
      {
        id: "glass",
        name: "Thủy Tinh",
        max: 3,
        desc: "+5 ATK, -10 HP",
        type: "PASSIVE",
        mod: { atk: 5, maxHp: -10 },
      },
      {
        id: "wisdom",
        name: "Thông Thái",
        max: 5,
        desc: "Tăng hiệu quả hồi năng lượng (HP Regen)",
        type: "PASSIVE",
        mod: { hpRegen: 2 },
      },
    ],
  },
  cleric: {
    id: "cleric",
    name: "Mục Sư",
    icon: Cross,
    color: "text-yellow-400",
    desc: "Khả năng hồi phục và sinh tồn tuyệt vời.",
    baseMod: { atk: 0, def: 3, maxHp: 40, luck: 0 },
    allowed: { weapon: ["MACE", "STAFF"], armor: ["ROBE", "PLATE"] },
    passiveDesc: "Hiệu quả sử dụng thuốc tăng 50%.",
    skills: [
      {
        id: "faith",
        name: "Đức Tin",
        max: 5,
        desc: "+10 Max HP",
        type: "PASSIVE",
        mod: { maxHp: 10 },
      },
      {
        id: "guardian",
        name: "Hộ Vệ",
        max: 3,
        desc: "+3 DEF",
        type: "PASSIVE",
        mod: { def: 3 },
      },
    ],
  },
};
