import {
  Book,
  Hammer,
  Heart,
  Scroll,
  Shield,
  Shirt,
  Star,
  Sword,
  Wand,
} from "lucide-react";

import type { ItemAffixDefinition, ItemTemplate } from "@/lib/gameTypes";

export const AFFIX_DB: ItemAffixDefinition[] = [
  { id: "sharp", name: "Sắc Bén", stat: "atk", val: 1, type: ["WEAPON"] },
  { id: "heavy", name: "Nặng Ký", stat: "atk", val: 2, type: ["WEAPON"] },
  {
    id: "lethal",
    name: "Chí Mạng",
    stat: "crit",
    val: 3,
    type: ["WEAPON", "ACCESSORY"],
  },
  { id: "hard", name: "Cứng Cáp", stat: "def", val: 1, type: ["ARMOR"] },
  {
    id: "vital",
    name: "Sinh Lực",
    stat: "maxHp",
    val: 10,
    type: ["ARMOR", "ACCESSORY"],
  },
  {
    id: "lucky",
    name: "May Mắn",
    stat: "luck",
    val: 1,
    type: ["ACCESSORY", "WEAPON"],
  },
];

export const ITEMS_DB: ItemTemplate[] = [
  {
    id: "pot_small",
    name: "Bình Máu Nhỏ",
    type: "CONSUMABLE",
    baseCost: 20,
    rarity: 1,
    baseVal: 30,
    descFormat: (val: number) => `Hồi ${val} HP`,
    useAction: "HEAL",
    icon: Heart,
  },
  {
    id: "pot_large",
    name: "Bình Máu Lớn",
    type: "CONSUMABLE",
    baseCost: 50,
    rarity: 2,
    baseVal: 80,
    descFormat: (val: number) => `Hồi ${val} HP`,
    useAction: "HEAL",
    icon: Heart,
  },
  {
    id: "respec",
    name: "Sách Lãng Quên",
    type: "CONSUMABLE",
    baseCost: 500,
    rarity: 4,
    baseVal: 0,
    descFormat: (_val: number) => "Hoàn trả toàn bộ điểm chỉ số và kỹ năng",
    useAction: "RESET_POINTS",
    icon: Book,
  },
  {
    id: "pot_str",
    name: "Thuốc Sức Mạnh",
    type: "CONSUMABLE",
    baseCost: 40,
    rarity: 2,
    baseVal: 5,
    descFormat: (val: number) => `+${val} ATK trong 3 lượt`,
    useAction: "APPLY_STRONG_ATK",
    icon: Sword,
  },
  {
    id: "scroll_shield",
    name: "Cuộn Bảo Vệ",
    type: "CONSUMABLE",
    baseCost: 60,
    rarity: 3,
    baseVal: 20,
    descFormat: (val: number) => `Tạo lá chắn ${val} sát thương`,
    useAction: "APPLY_SHIELD",
    icon: Scroll,
  },
  {
    id: "w_sword",
    name: "Kiếm Sắt",
    type: "WEAPON",
    subType: "SWORD",
    baseCost: 50,
    rarity: 1,
    icon: Sword,
    baseStats: { atk: 4 },
  },
  {
    id: "w_axe",
    name: "Rìu Chiến",
    type: "WEAPON",
    subType: "AXE",
    baseCost: 60,
    rarity: 2,
    icon: Hammer,
    baseStats: { atk: 6 },
  },
  {
    id: "w_dagger",
    name: "Dao Găm",
    type: "WEAPON",
    subType: "DAGGER",
    baseCost: 40,
    rarity: 1,
    icon: Sword,
    baseStats: { atk: 3, crit: 5 },
  },
  {
    id: "w_staff",
    name: "Gậy Phép",
    type: "WEAPON",
    subType: "STAFF",
    baseCost: 55,
    rarity: 2,
    icon: Wand,
    baseStats: { atk: 5 },
  },
  {
    id: "a_plate",
    name: "Giáp Tấm",
    type: "ARMOR",
    subType: "PLATE",
    baseCost: 80,
    rarity: 2,
    icon: Shield,
    baseStats: { def: 4, maxHp: 20 },
  },
  {
    id: "a_robe",
    name: "Áo Vải",
    type: "ARMOR",
    subType: "ROBE",
    baseCost: 30,
    rarity: 1,
    icon: Shirt,
    baseStats: { def: 1, maxHp: 10 },
  },
  {
    id: "a_leather",
    name: "Giáp Da",
    type: "ARMOR",
    subType: "LEATHER",
    baseCost: 40,
    rarity: 1,
    icon: Shirt,
    baseStats: { def: 2, maxHp: 15 },
  },
  {
    id: "ac_ring",
    name: "Nhẫn Lực",
    type: "ACCESSORY",
    baseCost: 100,
    rarity: 2,
    icon: Star,
    baseStats: { atk: 2, luck: 1 },
  },
];
